### ISSUE TITLE
AttributeError: module 'django.db.models' has no attribute 'permalink'

### ISSUE THREAD

**Issue by suyash2411** [cyface/django-termsandconditions#195]
from __future__ import unicode_literals
from django.db import models
from django.contrib.auth.models import User
from django.contrib.sites.models import Site
from six import python_2_unicode_compatible

@python_2_unicode_compatible
class Product(models.Model):
    """A generic Product"""
    name = models.CharField(blank=True, max_length=100)
    sites = models.ManyToManyField(Site)

    def __str__(self):
        return self.name

    @models.permalink
    def get_absolute_url(self):
        return ('product_detail', [self.id])

    def sites_str(self):
        return ', '.join([s.name for s in self.sites.all()])
    sites_str.short_description = 'sites'

@python_2_unicode_compatible
class Vote(models.Model):
    """A Vote on a Product"""
    user = models.ForeignKey(User, related_name='votes')
    product = models.ForeignKey(Product)
    site = models.ForeignKey(Site)
    score = models.FloatField()

    def __str__(self):
        return "Vote"

**Comment by cyface** [comment]
Hello! This package requires Django 2.2+.

 `@models.permalink` is deprecated since Django 1.11: https://docs.djangoproject.com/en/1.11/releases/1.11/#models-permalink-decorator

The `Permalink` decorator was removed in Django 2.1: https://docs.djangoproject.com/en/3.1/releases/2.1/#features-removed-in-2-1

So, you'll need to use the `reverse` function instead of `permalink`.  

Cheers!
