### ISSUE TITLE
Django 1.10+ support

### ISSUE THREAD

**Issue by ciarancourtney** [cyface/django-termsandconditions#23]
Are there any plans to support Django 1.10 and up?

A quick test against 1.11 gave the following stacktrace:

      File "/opt/master/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 82, in load_middleware
        mw_instance = middleware(handler)
    TypeError: object() takes no parameters

**Comment by cyface** [comment]
Hi there - I have had Travis set up to test against 1.10 for a while now, and it seems to be working well. I'll take a look at 1.11 over the next week or so.  Cheers!

**Comment by cyface** [comment]
Looks like was working fine with Django 1.11 if you are using MIDDLEWARE_CLASSES in your settings, but not if you were using MIDDLEWARE.  I updated the middleware in the just-posted version 1.1.12 so that it should work with both now.  Let me know if it doesn't work as expected.  Thanks for the report!
