### ISSUE TITLE
MIddleware causes 7 extra queries

### ISSUE THREAD

**Issue by raratiru** [cyface/django-termsandconditions#30]
> You can force protection of your whole site by using the T&C middleware. Once activated, any attempt to access an authenticated page will first check to see if the user has accepted the active T&Cs. This can be a performance impact, so you can also use the _TermsAndConditionsDecorator to protect specific views, or the pipeline setup to only check on account creation.

I read the warning. However, I use django-debug-toolbar and I see that middleware use causes 7 extra queries, while 5 of them are duplicated 5 times. Is this OK?

The same number of queries appears when I use `{% show_terms_if_not_agreed %}` in the `base.html` template.

**Comment by cyface** [comment]
Generally, since they are pulling the same thing over and over, the results will be cached by Django's DB layer, so it won't be going back to the DB every time.  I'm quite sure it could be optimized further, especially to make use of Django's cache layer to hold the result.  If you have suggestions on doing so, let me know!  Thank you!

**Comment by raratiru** [comment]
OK, using the django cache layer is a good idea. Thank you for mentioning it!
